### ISSUE TITLE
New geth 1.11 breaks dshackle

### ISSUE THREAD

**Issue by adrianchiforwm** [emeraldpay/dshackle#227]
https://github.com/ethereum/go-ethereum/pull/25570
https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0

```
Geth's JSON-RPC server has become more strict; the JSON-RPC spec requires the version field to be exactly "jsonrpc": "2.0". 
This is now verified by the server -- a change which is not backwards-compatible with non-conforming client implementations.
```

```
2023-21-02 12:09:39.493 | INFO  |  Multistream | State of ETH: height=16676781, status=[OK/3,SYNCING/1], lag=[0, 0, 0, NA], weak=[<new geth>]
2023-21-02 12:06:07.034 | INFO  | WsConnection | Connecting to WebSocket: ws://<new geth>:8546/
2023-21-02 12:06:07.465 | WARN  | WsConnection | Received error -32600 from ws://<new geth>:8546/: invalid request
2023-21-02 12:06:07.466 | WARN  | WsConnection | Received error -32600 from ws://<new geth>:8546/: invalid request
2023-21-02 12:06:07.466 | INFO  | WsConnection | Reconnect to ws://<new geth>:8546/ in 300000ms...
```

Looks like dshackle doesn't set the version in JSON-RPC requests so things like eth_syncing always think the node is behind (lag NA) and eth_subscribe websockets fail to establish.

cc @splix

**Comment by splix** [comment]
Fixed in #228

**Comment by adrianchiforwm** [comment]
@splix Thanks for the quick fix! Although eth_syncing is still broken, reports NA lag - missing the jsonrpc field. Once that's fixed, can we tag a new release and docker image? So dshackle can be ready in time for Capella.

**Comment by OscBacon** [comment]
Hey, could you please push a docker image with the fix? In the meantime I'll push one on my account

**Comment by splix** [comment]
@OscBacon it's `./gradlew jibDockerBuild` to install to a local Docker (and then `docker tag`/`docker push`) or `./gradlew jib -Pdocker=MYREMOTEDOCKERREPO` to push a remote docker directly from the build

**Comment by OscBacon** [comment]
Ah thanks @splix, not too familiar with Java.
Why hold off on pushing an image with these changes by the way?
